{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.1.0-ge91e6bb90bba",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.0-ge91e6bb90bba.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.0-ge91e6bb90bba.jar",
          "size": 42517752,
          "sha512": "392d4ac717ce439d81c2d0eb109cf2473d2dbff9412d69f5025682d2c444cd008ba8581960d8311fa277c5bdb30debb2846410faafafcfbf47d60e5e0cd46332",
          "sha256": "70fc3c0703b8550a8d95c2902af5b4562d654ccb860e920e016badf576b2492b",
          "sha1": "0a9da86dffb8764c1bacc4b0cdff14de516ce557",
          "md5": "51b043b2e213f8544e002d49142fa203"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.0-ge91e6bb90bba.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.0-ge91e6bb90bba.jar",
          "size": 42517752,
          "sha512": "392d4ac717ce439d81c2d0eb109cf2473d2dbff9412d69f5025682d2c444cd008ba8581960d8311fa277c5bdb30debb2846410faafafcfbf47d60e5e0cd46332",
          "sha256": "70fc3c0703b8550a8d95c2902af5b4562d654ccb860e920e016badf576b2492b",
          "sha1": "0a9da86dffb8764c1bacc4b0cdff14de516ce557",
          "md5": "51b043b2e213f8544e002d49142fa203"
        }
      ]
    }
  ]
}
