{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.2.0-g94a5729-6b7a3bf",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-g94a5729-6b7a3bf.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-g94a5729-6b7a3bf.jar",
          "size": 8004189,
          "sha512": "08f31509a418cb85a2a03350f50afa883fc6b97c47dffc871fe17ae5e4c3c873ee5fef283b272ea070548b2f8e1070fa922fc2d331eba620430bf5fc9edf9e0a",
          "sha256": "ace2fec02fc3a5e32f760e1448482d152946ed95657ac7f41a7404c201371904",
          "sha1": "6c5e7738626c4e011464415a0093494d22379187",
          "md5": "e66f02f3b289fe38f86f07fdb88de2c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-g94a5729-6b7a3bf.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-g94a5729-6b7a3bf.jar",
          "size": 8004189,
          "sha512": "08f31509a418cb85a2a03350f50afa883fc6b97c47dffc871fe17ae5e4c3c873ee5fef283b272ea070548b2f8e1070fa922fc2d331eba620430bf5fc9edf9e0a",
          "sha256": "ace2fec02fc3a5e32f760e1448482d152946ed95657ac7f41a7404c201371904",
          "sha1": "6c5e7738626c4e011464415a0093494d22379187",
          "md5": "e66f02f3b289fe38f86f07fdb88de2c5"
        }
      ]
    }
  ]
}
