{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "1.2.1-gabde383-fa29f94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.2.1-gabde383-fa29f94.jar",
          "url": "coakka-jvm-native-runtime-v2-1.2.1-gabde383-fa29f94.jar",
          "size": 16168832,
          "sha512": "7a68e4942e8ef034761314bb07abfe1db593a33c22bb88bbdba6b610fca6d967ed650ffea4889c0a9094767720c9e1ac206e6f4212da75c8d95240adff999d75",
          "sha256": "9c3ad0189641fae9490a908f60ee597cbade24002bcaa39d47e65c8cf53af818",
          "sha1": "85402d82cdb6e3a80a37971db8805b55fa1fe83f",
          "md5": "777bc8e2d481616f1ce5b203a8e6859f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.2.1-gabde383-fa29f94.jar",
          "url": "coakka-jvm-native-runtime-v2-1.2.1-gabde383-fa29f94.jar",
          "size": 16168832,
          "sha512": "7a68e4942e8ef034761314bb07abfe1db593a33c22bb88bbdba6b610fca6d967ed650ffea4889c0a9094767720c9e1ac206e6f4212da75c8d95240adff999d75",
          "sha256": "9c3ad0189641fae9490a908f60ee597cbade24002bcaa39d47e65c8cf53af818",
          "sha1": "85402d82cdb6e3a80a37971db8805b55fa1fe83f",
          "md5": "777bc8e2d481616f1ce5b203a8e6859f"
        }
      ]
    }
  ]
}
