{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "2.3.0-ga83ab412-3a84c7b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "2.3.0-ga83ab412-3a84c7b"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-2.3.0-ga83ab412-3a84c7b.jar",
          "url": "coakka-quarkus-extension-2.3.0-ga83ab412-3a84c7b.jar",
          "size": 10822,
          "sha512": "d097b6a9355db8a5aba680d44bc258eb4ba10650a5ee4aab488396b7f5b776376e19af511fbdc8957a27cc66278da5162dd6f2cb77c032f7228a37d4cb8fa1f8",
          "sha256": "a3c2ced532253e52a6c88da61db6560b6db380d3d2adc07744deb9302373fff3",
          "sha1": "dd516a913467a362a5d17c79ea1a73193e04e892",
          "md5": "bd85ba38f28b6b07dfbaf41539847d5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "2.3.0-ga83ab412-3a84c7b"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-2.3.0-ga83ab412-3a84c7b.jar",
          "url": "coakka-quarkus-extension-2.3.0-ga83ab412-3a84c7b.jar",
          "size": 10822,
          "sha512": "d097b6a9355db8a5aba680d44bc258eb4ba10650a5ee4aab488396b7f5b776376e19af511fbdc8957a27cc66278da5162dd6f2cb77c032f7228a37d4cb8fa1f8",
          "sha256": "a3c2ced532253e52a6c88da61db6560b6db380d3d2adc07744deb9302373fff3",
          "sha1": "dd516a913467a362a5d17c79ea1a73193e04e892",
          "md5": "bd85ba38f28b6b07dfbaf41539847d5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-2.3.0-ga83ab412-3a84c7b-sources.jar",
          "url": "coakka-quarkus-extension-2.3.0-ga83ab412-3a84c7b-sources.jar",
          "size": 5737,
          "sha512": "0795951c883846cc191eecb405c00382bc5ec6c1bb2d88907696d3ec4fc442e73a5965f18e7d937056d44d6c3f77b7474e0c82ba45cddb3b572aeb7f2f9d4db8",
          "sha256": "caed59696ad29345fa62afe66deeee663f76423a9e14bf2d82aa7a50b3c11d8d",
          "sha1": "43bd48565053c08c0de108a5b578b729a0e54ed6",
          "md5": "65b46a41d7ceb977234b74c43d16dd1c"
        }
      ]
    }
  ]
}
