{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "1.3.1-gbda2ef5-0a0aa76",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.3.1-gbda2ef5-0a0aa76.jar",
          "url": "coakka-jvm-native-runtime-v2-1.3.1-gbda2ef5-0a0aa76.jar",
          "size": 15624426,
          "sha512": "d6d01ec843bc16a4b5fcda89e29c49173934e9bdeadbbdd1dd5dac290fd969a68d0ebc45c47e8f47b4e2b966eae12ca3dfd5acf6335e146b9f88f8b5199aa726",
          "sha256": "7b2e6970df55ec4fa4000482951967c532418a90bdbf68af5370cb650cde663b",
          "sha1": "9ef69562eaa171a77c701a2dfde548c8d379409a",
          "md5": "4fa274bd91547308309734fb2cfd45f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.3.1-gbda2ef5-0a0aa76.jar",
          "url": "coakka-jvm-native-runtime-v2-1.3.1-gbda2ef5-0a0aa76.jar",
          "size": 15624426,
          "sha512": "d6d01ec843bc16a4b5fcda89e29c49173934e9bdeadbbdd1dd5dac290fd969a68d0ebc45c47e8f47b4e2b966eae12ca3dfd5acf6335e146b9f88f8b5199aa726",
          "sha256": "7b2e6970df55ec4fa4000482951967c532418a90bdbf68af5370cb650cde663b",
          "sha1": "9ef69562eaa171a77c701a2dfde548c8d379409a",
          "md5": "4fa274bd91547308309734fb2cfd45f0"
        }
      ]
    }
  ]
}
