{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "1.4.0-g2cee86bf-ec4902c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.4.0-g2cee86bf-ec4902c"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.4.0-g2cee86bf-ec4902c.jar",
          "url": "coakka-quarkus-extension-1.4.0-g2cee86bf-ec4902c.jar",
          "size": 10821,
          "sha512": "44f130c92b06a828792a1c295b84d4230d3919f1a11d74dab62c0d48e66f65eabe1708266576cb3e8feaf3429a25d3c3f3b190fef170611e93d6381bca62e358",
          "sha256": "cacc45cdfbed96229131926c5ec71606af039afa6b184d37ebe60924fb3b5979",
          "sha1": "8b927f36a6486384b4475a5468995e8c323a4a28",
          "md5": "6ff67d9313c9cc450f4362930b0957d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.4.0-g2cee86bf-ec4902c"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.4.0-g2cee86bf-ec4902c.jar",
          "url": "coakka-quarkus-extension-1.4.0-g2cee86bf-ec4902c.jar",
          "size": 10821,
          "sha512": "44f130c92b06a828792a1c295b84d4230d3919f1a11d74dab62c0d48e66f65eabe1708266576cb3e8feaf3429a25d3c3f3b190fef170611e93d6381bca62e358",
          "sha256": "cacc45cdfbed96229131926c5ec71606af039afa6b184d37ebe60924fb3b5979",
          "sha1": "8b927f36a6486384b4475a5468995e8c323a4a28",
          "md5": "6ff67d9313c9cc450f4362930b0957d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-1.4.0-g2cee86bf-ec4902c-sources.jar",
          "url": "coakka-quarkus-extension-1.4.0-g2cee86bf-ec4902c-sources.jar",
          "size": 5737,
          "sha512": "0795951c883846cc191eecb405c00382bc5ec6c1bb2d88907696d3ec4fc442e73a5965f18e7d937056d44d6c3f77b7474e0c82ba45cddb3b572aeb7f2f9d4db8",
          "sha256": "caed59696ad29345fa62afe66deeee663f76423a9e14bf2d82aa7a50b3c11d8d",
          "sha1": "43bd48565053c08c0de108a5b578b729a0e54ed6",
          "md5": "65b46a41d7ceb977234b74c43d16dd1c"
        }
      ]
    }
  ]
}
