{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.spring",
    "module": "coakka-spring-boot-starter",
    "version": "1.3.1-g0da8c2d9-8ff6f32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.1-g0da8c2d9-8ff6f32"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-1.3.1-g0da8c2d9-8ff6f32.jar",
          "url": "coakka-spring-boot-starter-1.3.1-g0da8c2d9-8ff6f32.jar",
          "size": 10990,
          "sha512": "b37ad9693cf0f5cdc818b4acba6cf877b49869d883333df210b9ada9be7c90292242b7a867fe875a979e5b9cc19a04ef1cc4594fe7e9add62b137f52ce8243af",
          "sha256": "71e4d4501520fb9c67827801be050534cc31e4925ff37d4d959833fa3cc6f1a5",
          "sha1": "cdc72771f745069e131a3d2d992b72bc49337c03",
          "md5": "f273e4b7bfbc14989773dd9ed0f5bbc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.1-g0da8c2d9-8ff6f32"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-1.3.1-g0da8c2d9-8ff6f32.jar",
          "url": "coakka-spring-boot-starter-1.3.1-g0da8c2d9-8ff6f32.jar",
          "size": 10990,
          "sha512": "b37ad9693cf0f5cdc818b4acba6cf877b49869d883333df210b9ada9be7c90292242b7a867fe875a979e5b9cc19a04ef1cc4594fe7e9add62b137f52ce8243af",
          "sha256": "71e4d4501520fb9c67827801be050534cc31e4925ff37d4d959833fa3cc6f1a5",
          "sha1": "cdc72771f745069e131a3d2d992b72bc49337c03",
          "md5": "f273e4b7bfbc14989773dd9ed0f5bbc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-spring-boot-starter-1.3.1-g0da8c2d9-8ff6f32-sources.jar",
          "url": "coakka-spring-boot-starter-1.3.1-g0da8c2d9-8ff6f32-sources.jar",
          "size": 5220,
          "sha512": "c66c355532a0711bcc46f7054cf563dbe7e4f63f0dfb2b0dd719460ee2dad3643b2ed9b11e38a06e8247bda81b2102d8a3f22def6e03acb3f6cb2ba82400f5bc",
          "sha256": "b14835ae7c6889624ac3eee234556957e6e8371adbcc2cb53c4c49395f1ae959",
          "sha1": "f2e3d924c3170e0eab8ff000c731110ff2840766",
          "md5": "ef009634362dc12c937d61df56215f21"
        }
      ]
    }
  ]
}
