{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "0.2.0-g11071541ea78",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.2.0-gb8ecfae-1107154"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-0.2.0-g11071541ea78.jar",
          "url": "coakka-quarkus-extension-0.2.0-g11071541ea78.jar",
          "size": 9510,
          "sha512": "947e3f9da0fcda0fefa6f2b4bcefe3af5ca1e79ee1bf0c48dbd26fe3065f79b3c7b33bfcefd0a9972ce0cd306ded0a46c071d9862e95e9fc2cc94a12979df52c",
          "sha256": "af14745aec4a57247868ff2f733280cedc8c1bd4eb9dc113d10312893bd6f78b",
          "sha1": "bbe62ff21b1aa966db2cec36e8df39088ed133e4",
          "md5": "e6c29c0070bbfbb3a4142b4677a4eb7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.2.0-gb8ecfae-1107154"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-0.2.0-g11071541ea78.jar",
          "url": "coakka-quarkus-extension-0.2.0-g11071541ea78.jar",
          "size": 9510,
          "sha512": "947e3f9da0fcda0fefa6f2b4bcefe3af5ca1e79ee1bf0c48dbd26fe3065f79b3c7b33bfcefd0a9972ce0cd306ded0a46c071d9862e95e9fc2cc94a12979df52c",
          "sha256": "af14745aec4a57247868ff2f733280cedc8c1bd4eb9dc113d10312893bd6f78b",
          "sha1": "bbe62ff21b1aa966db2cec36e8df39088ed133e4",
          "md5": "e6c29c0070bbfbb3a4142b4677a4eb7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-0.2.0-g11071541ea78-sources.jar",
          "url": "coakka-quarkus-extension-0.2.0-g11071541ea78-sources.jar",
          "size": 5110,
          "sha512": "e4cc5d8c196f6d1ce2f0329b001023494b82de037fc538399d49bc8a580d763d2fa6580c1269f8725c775795f2bd1ebe6677b54b39d2c758338dcf3fffea025c",
          "sha256": "df23a1f08d87eef6944f45bfca6a5e3f62c46035872755b7d0d9663e40e74962",
          "sha1": "c62d715a944c2e8ce87a497575967b2c7b8be25f",
          "md5": "d98bcfeeac12753f90c4dfba7ae81edc"
        }
      ]
    }
  ]
}
