{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.phuong-tran.coakka",
    "module": "runtime",
    "version": "2.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-2.5.3.jar",
          "url": "runtime-2.5.3.jar",
          "size": 8319405,
          "sha512": "8530901bae2fb0fa0bb6ad0ae33e55c3ee3f15428be1132e3e7e6186f9b155493c515d2a7f5baa42ea9ca9aa6457446bb6d07563b3549b11672f98934c18cb97",
          "sha256": "36a3ca8d0f04a5dc41de9647c665dc80c4839dd6be974b010e6df096b11f8068",
          "sha1": "a54c4f4cb6dbe349439910deec784237c1bc83c0",
          "md5": "46cd7e94433dc5e8267e46e903d46648"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-2.5.3.jar",
          "url": "runtime-2.5.3.jar",
          "size": 8319405,
          "sha512": "8530901bae2fb0fa0bb6ad0ae33e55c3ee3f15428be1132e3e7e6186f9b155493c515d2a7f5baa42ea9ca9aa6457446bb6d07563b3549b11672f98934c18cb97",
          "sha256": "36a3ca8d0f04a5dc41de9647c665dc80c4839dd6be974b010e6df096b11f8068",
          "sha1": "a54c4f4cb6dbe349439910deec784237c1bc83c0",
          "md5": "46cd7e94433dc5e8267e46e903d46648"
        }
      ]
    }
  ]
}
