{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "0.2.0-g1c2694b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.2.0-gc124a9e-2bab9ee"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-0.2.0-g1c2694b.jar",
          "url": "coakka-quarkus-extension-0.2.0-g1c2694b.jar",
          "size": 9510,
          "sha512": "e0a27dab5ca2e36ebdffeaafc5bd43ff84090fd5dbdfea65bbc217bac2c2bf059d0821fa6e8dff2408d3f5782cfaabe59856d092bf3a465ec765dde989740127",
          "sha256": "a79f866e8c71b37584d236f3b57d08ec2b60dc790f27b4fd73c4a90e40f909e0",
          "sha1": "bd4b39309c041fefcf30f15be57f2ce44a093f2d",
          "md5": "7ad1f5e884cead745224b39cc363d43c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.2.0-gc124a9e-2bab9ee"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-0.2.0-g1c2694b.jar",
          "url": "coakka-quarkus-extension-0.2.0-g1c2694b.jar",
          "size": 9510,
          "sha512": "e0a27dab5ca2e36ebdffeaafc5bd43ff84090fd5dbdfea65bbc217bac2c2bf059d0821fa6e8dff2408d3f5782cfaabe59856d092bf3a465ec765dde989740127",
          "sha256": "a79f866e8c71b37584d236f3b57d08ec2b60dc790f27b4fd73c4a90e40f909e0",
          "sha1": "bd4b39309c041fefcf30f15be57f2ce44a093f2d",
          "md5": "7ad1f5e884cead745224b39cc363d43c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-0.2.0-g1c2694b-sources.jar",
          "url": "coakka-quarkus-extension-0.2.0-g1c2694b-sources.jar",
          "size": 5110,
          "sha512": "e4cc5d8c196f6d1ce2f0329b001023494b82de037fc538399d49bc8a580d763d2fa6580c1269f8725c775795f2bd1ebe6677b54b39d2c758338dcf3fffea025c",
          "sha256": "df23a1f08d87eef6944f45bfca6a5e3f62c46035872755b7d0d9663e40e74962",
          "sha1": "c62d715a944c2e8ce87a497575967b2c7b8be25f",
          "md5": "d98bcfeeac12753f90c4dfba7ae81edc"
        }
      ]
    }
  ]
}
