{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.spring",
    "module": "coakka-spring-boot-starter",
    "version": "1.3.1-g0a0aa76",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.1-gbda2ef5-0a0aa76"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-1.3.1-g0a0aa76.jar",
          "url": "coakka-spring-boot-starter-1.3.1-g0a0aa76.jar",
          "size": 10988,
          "sha512": "f3190464318c87dafb23520915a9af8e3fd5507d5c8580d6404764b3ab23adec51f95b1cf457371e471fd8b4c531c197f13cdf91ba6e62ae7086df02587926f8",
          "sha256": "84b4223ea0cbc2cfbc72fb211d30a9c3d086fb8617bcbe5fe02a69f9ffe5308f",
          "sha1": "061addc866e2445012c81e51c932c05389a4dccd",
          "md5": "1f5ba2a11a45ccfce6cec3e23eb6571c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.1-gbda2ef5-0a0aa76"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-1.3.1-g0a0aa76.jar",
          "url": "coakka-spring-boot-starter-1.3.1-g0a0aa76.jar",
          "size": 10988,
          "sha512": "f3190464318c87dafb23520915a9af8e3fd5507d5c8580d6404764b3ab23adec51f95b1cf457371e471fd8b4c531c197f13cdf91ba6e62ae7086df02587926f8",
          "sha256": "84b4223ea0cbc2cfbc72fb211d30a9c3d086fb8617bcbe5fe02a69f9ffe5308f",
          "sha1": "061addc866e2445012c81e51c932c05389a4dccd",
          "md5": "1f5ba2a11a45ccfce6cec3e23eb6571c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-spring-boot-starter-1.3.1-g0a0aa76-sources.jar",
          "url": "coakka-spring-boot-starter-1.3.1-g0a0aa76-sources.jar",
          "size": 5220,
          "sha512": "c66c355532a0711bcc46f7054cf563dbe7e4f63f0dfb2b0dd719460ee2dad3643b2ed9b11e38a06e8247bda81b2102d8a3f22def6e03acb3f6cb2ba82400f5bc",
          "sha256": "b14835ae7c6889624ac3eee234556957e6e8371adbcc2cb53c4c49395f1ae959",
          "sha1": "f2e3d924c3170e0eab8ff000c731110ff2840766",
          "md5": "ef009634362dc12c937d61df56215f21"
        }
      ]
    }
  ]
}
