{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.logger",
    "module": "coakka-jvm-native-logger",
    "version": "1.2.1-gf50756ebff0d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "coakka-jvm-native-logger-1.2.1-gf50756ebff0d.jar",
          "url": "coakka-jvm-native-logger-1.2.1-gf50756ebff0d.jar",
          "size": 1963997,
          "sha512": "76404a4c34a8790127f17d0a311b87fbbf32bfeb033a91a03022df73c11f83bfe6feb3067d84cfe2924d7f265462b8cd75a06ea168eeb62d3aca3a752cad5ae7",
          "sha256": "6c3ae767883f11da9b183803b1696964279120e6a9b55286bcf9f304ee4a6bea",
          "sha1": "a4001a2073e0335ecafcb86163cbf68239ffb88c",
          "md5": "117ff24e75173f3dffa64ac05e8d60de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-logger-1.2.1-gf50756ebff0d.jar",
          "url": "coakka-jvm-native-logger-1.2.1-gf50756ebff0d.jar",
          "size": 1963997,
          "sha512": "76404a4c34a8790127f17d0a311b87fbbf32bfeb033a91a03022df73c11f83bfe6feb3067d84cfe2924d7f265462b8cd75a06ea168eeb62d3aca3a752cad5ae7",
          "sha256": "6c3ae767883f11da9b183803b1696964279120e6a9b55286bcf9f304ee4a6bea",
          "sha1": "a4001a2073e0335ecafcb86163cbf68239ffb88c",
          "md5": "117ff24e75173f3dffa64ac05e8d60de"
        }
      ]
    }
  ]
}
