{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.2.0-gb8ecfae-1107154",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "size": 12338412,
          "sha512": "879bb26f52bb929d67a4581bcde4e5bc4b5d31a42ddc21ac8fb00b7d7f90d07ee8945d83423e129f60acc090368e892c5ca377459d1c37ca0a181cda8179cf43",
          "sha256": "9041f61d0a21a93d175603547608657ec7252170ebdf5304a17ffc5c9c7d9474",
          "sha1": "9785c2eb4591dbd8b3e0e2feabb1283915484b57",
          "md5": "e90b5dc94a847fd66a6733ffdf07224a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "size": 12338412,
          "sha512": "879bb26f52bb929d67a4581bcde4e5bc4b5d31a42ddc21ac8fb00b7d7f90d07ee8945d83423e129f60acc090368e892c5ca377459d1c37ca0a181cda8179cf43",
          "sha256": "9041f61d0a21a93d175603547608657ec7252170ebdf5304a17ffc5c9c7d9474",
          "sha1": "9785c2eb4591dbd8b3e0e2feabb1283915484b57",
          "md5": "e90b5dc94a847fd66a6733ffdf07224a"
        }
      ]
    }
  ]
}
