{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.2.0-gb8ecfae-1107154",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "size": 8358966,
          "sha512": "fc4e9139cfb3a60fa39d446cd83e073ae18ab5c56e22d3a5bca064f542675f5beb47d612c3f239857b99e95114ddab468732508820d7c2a8f51820a35c41159c",
          "sha256": "9e9683e92fda221ae9b293b2d86e948044d6b00631082e802c342eebf93ef80e",
          "sha1": "3a8219d2bde58cf658f1e2e547cf79dc9fe00a1e",
          "md5": "624e1c7642eda921f11cd716ac1ecfe7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "size": 8358966,
          "sha512": "fc4e9139cfb3a60fa39d446cd83e073ae18ab5c56e22d3a5bca064f542675f5beb47d612c3f239857b99e95114ddab468732508820d7c2a8f51820a35c41159c",
          "sha256": "9e9683e92fda221ae9b293b2d86e948044d6b00631082e802c342eebf93ef80e",
          "sha1": "3a8219d2bde58cf658f1e2e547cf79dc9fe00a1e",
          "md5": "624e1c7642eda921f11cd716ac1ecfe7"
        }
      ]
    }
  ]
}
