{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.2.0-gb8ecfae-1107154",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "size": 8503920,
          "sha512": "a7f042bb7a02f787ef799e06cb94faa05fd5b8e9fcfe853b73f0e26205077d760ccac31c7139683288b49c21eece8e3dc129569700ce8785f92327e06c0f1c28",
          "sha256": "df6c913b78c9d4d430aa607208b8fd9c5a89f94d2677250f518bd7c5fe04ad79",
          "sha1": "bd62e3434471cbafdbe777ab1d36cb21706b2905",
          "md5": "464c20e4c70bf799b447cbd169fc82cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-1107154.jar",
          "size": 8503920,
          "sha512": "a7f042bb7a02f787ef799e06cb94faa05fd5b8e9fcfe853b73f0e26205077d760ccac31c7139683288b49c21eece8e3dc129569700ce8785f92327e06c0f1c28",
          "sha256": "df6c913b78c9d4d430aa607208b8fd9c5a89f94d2677250f518bd7c5fe04ad79",
          "sha1": "bd62e3434471cbafdbe777ab1d36cb21706b2905",
          "md5": "464c20e4c70bf799b447cbd169fc82cd"
        }
      ]
    }
  ]
}
