{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "1.3.3-g282f3ad-657ec79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.3.3-g282f3ad-657ec79.jar",
          "url": "coakka-jvm-native-runtime-v2-1.3.3-g282f3ad-657ec79.jar",
          "size": 14221467,
          "sha512": "11116d9281d44d4cdc76ca00cc5bfd93bb58fc127b161edfb3ad44eddc1954b62dfbea7d879a77062eb5291a9cf412614d0593eab21728bb7db1b86fca2d5734",
          "sha256": "a4fa9227923a4de46fcd9d2c359e908bddf6d5e24631f74d7f78f034ff920622",
          "sha1": "c1540fe0f62189558c9c276a7f7f3015565b1453",
          "md5": "c0c5ed5455ca660bb06555364a5d515c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.3.3-g282f3ad-657ec79.jar",
          "url": "coakka-jvm-native-runtime-v2-1.3.3-g282f3ad-657ec79.jar",
          "size": 14221467,
          "sha512": "11116d9281d44d4cdc76ca00cc5bfd93bb58fc127b161edfb3ad44eddc1954b62dfbea7d879a77062eb5291a9cf412614d0593eab21728bb7db1b86fca2d5734",
          "sha256": "a4fa9227923a4de46fcd9d2c359e908bddf6d5e24631f74d7f78f034ff920622",
          "sha1": "c1540fe0f62189558c9c276a7f7f3015565b1453",
          "md5": "c0c5ed5455ca660bb06555364a5d515c"
        }
      ]
    }
  ]
}
