{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.1.0-g0cb644340467-cfb8ee4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.0-g0cb644340467-cfb8ee4.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.0-g0cb644340467-cfb8ee4.jar",
          "size": 16393966,
          "sha512": "cb5c2f54218e15d89c8321acc7d9d4974a64fd795d63a8461b37e12df8cdfb5ca41813065ebaf40f4465878904e2c60a1b5a5e47da4bbb988a47c3ad48a3853a",
          "sha256": "ff2b70d4e6531444a9fc391ba0c00ccf0ea7b995a7877be9da3eb34381c78338",
          "sha1": "b2ff49abdaa827c56bc5f95d626412b1e2d2e5a4",
          "md5": "8a5aecbdc5ff63f64317bf261c421fd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.0-g0cb644340467-cfb8ee4.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.0-g0cb644340467-cfb8ee4.jar",
          "size": 16393966,
          "sha512": "cb5c2f54218e15d89c8321acc7d9d4974a64fd795d63a8461b37e12df8cdfb5ca41813065ebaf40f4465878904e2c60a1b5a5e47da4bbb988a47c3ad48a3853a",
          "sha256": "ff2b70d4e6531444a9fc391ba0c00ccf0ea7b995a7877be9da3eb34381c78338",
          "sha1": "b2ff49abdaa827c56bc5f95d626412b1e2d2e5a4",
          "md5": "8a5aecbdc5ff63f64317bf261c421fd0"
        }
      ]
    }
  ]
}
