{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.1.0-g65b36b8ad2ec",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.0-g65b36b8ad2ec.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.0-g65b36b8ad2ec.jar",
          "size": 1892071,
          "sha512": "de585e1aae7334e7371108ef47122b0dedc124bde1a65a694523357d2434cd7e63f48f297f09840c876b4ac837f5b5b4eae5e2bb7edd289ab98e6471f2c24625",
          "sha256": "d842a00631b562fc1646814d0dd33d0f3a292283c34014c662b8600a1eab56e4",
          "sha1": "286d67ea76a4b5439e250f1ad016904af6f44e26",
          "md5": "cb9925aaa3946592391939ca969c139d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.0-g65b36b8ad2ec.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.0-g65b36b8ad2ec.jar",
          "size": 1892071,
          "sha512": "de585e1aae7334e7371108ef47122b0dedc124bde1a65a694523357d2434cd7e63f48f297f09840c876b4ac837f5b5b4eae5e2bb7edd289ab98e6471f2c24625",
          "sha256": "d842a00631b562fc1646814d0dd33d0f3a292283c34014c662b8600a1eab56e4",
          "sha1": "286d67ea76a4b5439e250f1ad016904af6f44e26",
          "md5": "cb9925aaa3946592391939ca969c139d"
        }
      ]
    }
  ]
}
