{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.2.0-gb8ecfae-2d085e5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-2d085e5.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-2d085e5.jar",
          "size": 13697981,
          "sha512": "16b997847c20f7a1e1a88121ea1b1a57a038e031b453f5bfd5e3c32fbd130403241848433c2124666b268916c6af6b542bd6222415d47d364599243b27d6970e",
          "sha256": "4b62cb3bcb2df6b7bdcab177ee2fa5e9e0765fa8aaa6e86a609d40b2ba556c43",
          "sha1": "61a9288db309ca525c3ef61dfb59fdc7b15ce66a",
          "md5": "1a400ff4801cd26569f15f1961cd77d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-2d085e5.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gb8ecfae-2d085e5.jar",
          "size": 13697981,
          "sha512": "16b997847c20f7a1e1a88121ea1b1a57a038e031b453f5bfd5e3c32fbd130403241848433c2124666b268916c6af6b542bd6222415d47d364599243b27d6970e",
          "sha256": "4b62cb3bcb2df6b7bdcab177ee2fa5e9e0765fa8aaa6e86a609d40b2ba556c43",
          "sha1": "61a9288db309ca525c3ef61dfb59fdc7b15ce66a",
          "md5": "1a400ff4801cd26569f15f1961cd77d2"
        }
      ]
    }
  ]
}
