{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "0.2.0-g2d085e5923d9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.2.0-gb8ecfae-2d085e5"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-0.2.0-g2d085e5923d9.jar",
          "url": "coakka-quarkus-extension-0.2.0-g2d085e5923d9.jar",
          "size": 9509,
          "sha512": "9ad64b21a15c5bbe6544e973756b9c29861d4647ed60316261ad4e3dbd387d20a75741c76c7d5933e6e8206ed1525b8f743f65a88d714bea5fe49522466e1a0d",
          "sha256": "63fba294f20d4c6bb07c45f1f317c99dc44faf4c488c0e8e3ee43d7a01cfd989",
          "sha1": "f6a373ff7e79c581322c43660a35ff9c345a74d7",
          "md5": "4c3388a127ccbf7cc91e2939c3f7207e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.2.0-gb8ecfae-2d085e5"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-0.2.0-g2d085e5923d9.jar",
          "url": "coakka-quarkus-extension-0.2.0-g2d085e5923d9.jar",
          "size": 9509,
          "sha512": "9ad64b21a15c5bbe6544e973756b9c29861d4647ed60316261ad4e3dbd387d20a75741c76c7d5933e6e8206ed1525b8f743f65a88d714bea5fe49522466e1a0d",
          "sha256": "63fba294f20d4c6bb07c45f1f317c99dc44faf4c488c0e8e3ee43d7a01cfd989",
          "sha1": "f6a373ff7e79c581322c43660a35ff9c345a74d7",
          "md5": "4c3388a127ccbf7cc91e2939c3f7207e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-0.2.0-g2d085e5923d9-sources.jar",
          "url": "coakka-quarkus-extension-0.2.0-g2d085e5923d9-sources.jar",
          "size": 5110,
          "sha512": "e4cc5d8c196f6d1ce2f0329b001023494b82de037fc538399d49bc8a580d763d2fa6580c1269f8725c775795f2bd1ebe6677b54b39d2c758338dcf3fffea025c",
          "sha256": "df23a1f08d87eef6944f45bfca6a5e3f62c46035872755b7d0d9663e40e74962",
          "sha1": "c62d715a944c2e8ce87a497575967b2c7b8be25f",
          "md5": "d98bcfeeac12753f90c4dfba7ae81edc"
        }
      ]
    }
  ]
}
