{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "1.3.2-gcaff6d6d-6d5ea58",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.2-gcaff6d6d-6d5ea58"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.3.2-gcaff6d6d-6d5ea58.jar",
          "url": "coakka-quarkus-extension-1.3.2-gcaff6d6d-6d5ea58.jar",
          "size": 9509,
          "sha512": "bee57997866acc04ff600ff8fe9efa5260faaf01f5bd8bc5c473660fa437cfb05215eabd212cbea0a6f04138b1b54716bb462bb5a313d8ea3d8a0d1d95df8a37",
          "sha256": "1510d5d46bfa228567e70b235fc13c4ad1bd2d480b0f164afd587e638cfbf485",
          "sha1": "8300f13c999bfee96d678b937834b9a97580c211",
          "md5": "a818898696f771a18fae42e9e37551b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.2-gcaff6d6d-6d5ea58"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.3.2-gcaff6d6d-6d5ea58.jar",
          "url": "coakka-quarkus-extension-1.3.2-gcaff6d6d-6d5ea58.jar",
          "size": 9509,
          "sha512": "bee57997866acc04ff600ff8fe9efa5260faaf01f5bd8bc5c473660fa437cfb05215eabd212cbea0a6f04138b1b54716bb462bb5a313d8ea3d8a0d1d95df8a37",
          "sha256": "1510d5d46bfa228567e70b235fc13c4ad1bd2d480b0f164afd587e638cfbf485",
          "sha1": "8300f13c999bfee96d678b937834b9a97580c211",
          "md5": "a818898696f771a18fae42e9e37551b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-1.3.2-gcaff6d6d-6d5ea58-sources.jar",
          "url": "coakka-quarkus-extension-1.3.2-gcaff6d6d-6d5ea58-sources.jar",
          "size": 5110,
          "sha512": "e4cc5d8c196f6d1ce2f0329b001023494b82de037fc538399d49bc8a580d763d2fa6580c1269f8725c775795f2bd1ebe6677b54b39d2c758338dcf3fffea025c",
          "sha256": "df23a1f08d87eef6944f45bfca6a5e3f62c46035872755b7d0d9663e40e74962",
          "sha1": "c62d715a944c2e8ce87a497575967b2c7b8be25f",
          "md5": "d98bcfeeac12753f90c4dfba7ae81edc"
        }
      ]
    }
  ]
}
