{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "1.3.3-g282f3ad-657ec79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.3-g282f3ad-657ec79"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.3.3-g282f3ad-657ec79.jar",
          "url": "coakka-quarkus-extension-1.3.3-g282f3ad-657ec79.jar",
          "size": 9509,
          "sha512": "24031ec5cbb177969d710f51f34892a506f145ee7f4270eaf74947f9b2aacf6471497bcfba1072024b5c70e36db22935434e5a3b80d97d955689e7a5e09db19b",
          "sha256": "c24b0e5a3f93dc76932cacf9154a9ef947ad5e1c27ac450112f7afa2b56a5a61",
          "sha1": "dbcdde9cb2a42ce4693c6706ed73eb0237a5beab",
          "md5": "a83b0da1e4f62da9fe697c7fabc5ee82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.3-g282f3ad-657ec79"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.3.3-g282f3ad-657ec79.jar",
          "url": "coakka-quarkus-extension-1.3.3-g282f3ad-657ec79.jar",
          "size": 9509,
          "sha512": "24031ec5cbb177969d710f51f34892a506f145ee7f4270eaf74947f9b2aacf6471497bcfba1072024b5c70e36db22935434e5a3b80d97d955689e7a5e09db19b",
          "sha256": "c24b0e5a3f93dc76932cacf9154a9ef947ad5e1c27ac450112f7afa2b56a5a61",
          "sha1": "dbcdde9cb2a42ce4693c6706ed73eb0237a5beab",
          "md5": "a83b0da1e4f62da9fe697c7fabc5ee82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-1.3.3-g282f3ad-657ec79-sources.jar",
          "url": "coakka-quarkus-extension-1.3.3-g282f3ad-657ec79-sources.jar",
          "size": 5110,
          "sha512": "e4cc5d8c196f6d1ce2f0329b001023494b82de037fc538399d49bc8a580d763d2fa6580c1269f8725c775795f2bd1ebe6677b54b39d2c758338dcf3fffea025c",
          "sha256": "df23a1f08d87eef6944f45bfca6a5e3f62c46035872755b7d0d9663e40e74962",
          "sha1": "c62d715a944c2e8ce87a497575967b2c7b8be25f",
          "md5": "d98bcfeeac12753f90c4dfba7ae81edc"
        }
      ]
    }
  ]
}
