{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.spring",
    "module": "coakka-spring-boot-starter",
    "version": "2.3.0-ga83ab412-3a84c7b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "2.3.0-ga83ab412-3a84c7b"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-2.3.0-ga83ab412-3a84c7b.jar",
          "url": "coakka-spring-boot-starter-2.3.0-ga83ab412-3a84c7b.jar",
          "size": 12815,
          "sha512": "a215ef401d3776383e7f5b01fb5db5901861d7e21866e659bd5fb827706aaebce035b9fd323ebbf5fc83271bf714d960ef6f2203b99f2784107401543197554c",
          "sha256": "40a32f38b8f27c5153c813c022fe123ee61479a6972dee013c5fb7ff009200a0",
          "sha1": "b98d4fff334a037ba5ce50da7d0c9751dac845cd",
          "md5": "463a20bed64e45e53d9014413fbed448"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "2.3.0-ga83ab412-3a84c7b"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-2.3.0-ga83ab412-3a84c7b.jar",
          "url": "coakka-spring-boot-starter-2.3.0-ga83ab412-3a84c7b.jar",
          "size": 12815,
          "sha512": "a215ef401d3776383e7f5b01fb5db5901861d7e21866e659bd5fb827706aaebce035b9fd323ebbf5fc83271bf714d960ef6f2203b99f2784107401543197554c",
          "sha256": "40a32f38b8f27c5153c813c022fe123ee61479a6972dee013c5fb7ff009200a0",
          "sha1": "b98d4fff334a037ba5ce50da7d0c9751dac845cd",
          "md5": "463a20bed64e45e53d9014413fbed448"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-spring-boot-starter-2.3.0-ga83ab412-3a84c7b-sources.jar",
          "url": "coakka-spring-boot-starter-2.3.0-ga83ab412-3a84c7b-sources.jar",
          "size": 6116,
          "sha512": "5309258868c1e37edd5803a5d76de8088bcf123839264080b289bd5b0e7977d1ab307dee57e5ba94fa589b8767c7943c55f74af088178e17e08e93a246b077ca",
          "sha256": "f1b460fc70e76573c9c7e0f712b6aebfaa44412928baf829f1ba3ed8a1fe65ba",
          "sha1": "cd8b01cba1b7292ee9e37fef0ba770f3ec09af02",
          "md5": "f4eda03c0b3189d60cf17065934c45a5"
        }
      ]
    }
  ]
}
