{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.spring",
    "module": "coakka-spring-boot-starter",
    "version": "0.1.0-g432bd75d3e4b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.1.1-g22f571fd955c"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-0.1.0-g432bd75d3e4b.jar",
          "url": "coakka-spring-boot-starter-0.1.0-g432bd75d3e4b.jar",
          "size": 10917,
          "sha512": "8517912b0eac1c60268b688bd55293518bd34d517d0dd8487ac74e417f174dd830d132fad517197c768b777d8bc0d4a9cd4d11b0040e7bfe554bcda571c0e051",
          "sha256": "ccbd945820183cef6e39a2a7fae8c665ea9ec83e7a4b7f9621cb74b4bad7a194",
          "sha1": "fcf4f40de7c8612b038b25c4f00ae2c6cca82e04",
          "md5": "cbb6ed885ca870fa70e23ab8d02f6b69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.1.1-g22f571fd955c"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-0.1.0-g432bd75d3e4b.jar",
          "url": "coakka-spring-boot-starter-0.1.0-g432bd75d3e4b.jar",
          "size": 10917,
          "sha512": "8517912b0eac1c60268b688bd55293518bd34d517d0dd8487ac74e417f174dd830d132fad517197c768b777d8bc0d4a9cd4d11b0040e7bfe554bcda571c0e051",
          "sha256": "ccbd945820183cef6e39a2a7fae8c665ea9ec83e7a4b7f9621cb74b4bad7a194",
          "sha1": "fcf4f40de7c8612b038b25c4f00ae2c6cca82e04",
          "md5": "cbb6ed885ca870fa70e23ab8d02f6b69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-spring-boot-starter-0.1.0-g432bd75d3e4b-sources.jar",
          "url": "coakka-spring-boot-starter-0.1.0-g432bd75d3e4b-sources.jar",
          "size": 5209,
          "sha512": "5dde1efd71436e6f76f3487864162af8dca8b8c31b379c272f0254a884e0bfadfb9ee84af75a146b7b51cf0b97c6a4486ea86ac3eb80f8c3502e48091b97d764",
          "sha256": "c6912ecb7980482790ff8ca0c2433aa125eebf69e0ec7c2ab3ee1d8aa7213466",
          "sha1": "b203818f32ca54cc4421a0aa86ad14f67a9a0e37",
          "md5": "3b5c1bcde8ae6962aee1fcb32e29d523"
        }
      ]
    }
  ]
}
