{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.spring",
    "module": "coakka-spring-boot-starter",
    "version": "0.1.0-g90d825857466",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.1.0-g22f571fd955c"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-0.1.0-g90d825857466.jar",
          "url": "coakka-spring-boot-starter-0.1.0-g90d825857466.jar",
          "size": 10811,
          "sha512": "9ce1752bf8d7ce547232b4108e1d4b799f3ee2cdaca5238ff80f43566a606182f12f3e26aae2fa57ed2ea1ff03a80b095e2a6689d48568b218a29c10bc142500",
          "sha256": "f7480c7b5f35acd7215574f8646075e6bb779b7452c6e683dd18957221a27144",
          "sha1": "0b54b61dc37c5e3f5482421ed5778c58656b57db",
          "md5": "1d83e5b2cef7a7f0f3340e61e747defa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "0.1.0-g22f571fd955c"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-0.1.0-g90d825857466.jar",
          "url": "coakka-spring-boot-starter-0.1.0-g90d825857466.jar",
          "size": 10811,
          "sha512": "9ce1752bf8d7ce547232b4108e1d4b799f3ee2cdaca5238ff80f43566a606182f12f3e26aae2fa57ed2ea1ff03a80b095e2a6689d48568b218a29c10bc142500",
          "sha256": "f7480c7b5f35acd7215574f8646075e6bb779b7452c6e683dd18957221a27144",
          "sha1": "0b54b61dc37c5e3f5482421ed5778c58656b57db",
          "md5": "1d83e5b2cef7a7f0f3340e61e747defa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-spring-boot-starter-0.1.0-g90d825857466-sources.jar",
          "url": "coakka-spring-boot-starter-0.1.0-g90d825857466-sources.jar",
          "size": 5209,
          "sha512": "5dde1efd71436e6f76f3487864162af8dca8b8c31b379c272f0254a884e0bfadfb9ee84af75a146b7b51cf0b97c6a4486ea86ac3eb80f8c3502e48091b97d764",
          "sha256": "c6912ecb7980482790ff8ca0c2433aa125eebf69e0ec7c2ab3ee1d8aa7213466",
          "sha1": "b203818f32ca54cc4421a0aa86ad14f67a9a0e37",
          "md5": "3b5c1bcde8ae6962aee1fcb32e29d523"
        }
      ]
    }
  ]
}
