{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.1.1-g22f571fd955c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.1-g22f571fd955c.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.1-g22f571fd955c.jar",
          "size": 37792868,
          "sha512": "cdff784f340a5f53eb4ef2921fd937508f67c0f501fee9f69ac3cef90fddeff3b2c6001924b43bcb8865c972a8d9f586d35d9ea06ff2d06bfc605615b20d0466",
          "sha256": "b322b82cf33cd6f1f5270df11e353b19ec9528bfbf8ea9ff94214b7d3c017d30",
          "sha1": "4ed195064447bc9999e90c391ca5fd9baa949738",
          "md5": "f1841fad922d88989f5516a9475b01ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.1-g22f571fd955c.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.1-g22f571fd955c.jar",
          "size": 37792868,
          "sha512": "cdff784f340a5f53eb4ef2921fd937508f67c0f501fee9f69ac3cef90fddeff3b2c6001924b43bcb8865c972a8d9f586d35d9ea06ff2d06bfc605615b20d0466",
          "sha256": "b322b82cf33cd6f1f5270df11e353b19ec9528bfbf8ea9ff94214b7d3c017d30",
          "sha1": "4ed195064447bc9999e90c391ca5fd9baa949738",
          "md5": "f1841fad922d88989f5516a9475b01ed"
        }
      ]
    }
  ]
}
