{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "2.4.0-gc2f53117-0afb5e9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "2.4.0-gc2f53117-0afb5e9"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-2.4.0-gc2f53117-0afb5e9.jar",
          "url": "coakka-quarkus-extension-2.4.0-gc2f53117-0afb5e9.jar",
          "size": 10822,
          "sha512": "d8ae2424b45c4607c8926e5ae3a7c982a013b073b8585abcb068ef55d2df96377ef667bb18dd4ed13ce734926f53aa267a3c775db11ccd246e19acdfe6288566",
          "sha256": "6f5f06d09b84127983de5cb7567a35888080b9cc004bce30cfc91a78c54585c6",
          "sha1": "052efa3324c38f8f7e171a73d8aaf10f5c7388ee",
          "md5": "2cb0cb7962a0cb82045fedd3d8a51b28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "2.4.0-gc2f53117-0afb5e9"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-2.4.0-gc2f53117-0afb5e9.jar",
          "url": "coakka-quarkus-extension-2.4.0-gc2f53117-0afb5e9.jar",
          "size": 10822,
          "sha512": "d8ae2424b45c4607c8926e5ae3a7c982a013b073b8585abcb068ef55d2df96377ef667bb18dd4ed13ce734926f53aa267a3c775db11ccd246e19acdfe6288566",
          "sha256": "6f5f06d09b84127983de5cb7567a35888080b9cc004bce30cfc91a78c54585c6",
          "sha1": "052efa3324c38f8f7e171a73d8aaf10f5c7388ee",
          "md5": "2cb0cb7962a0cb82045fedd3d8a51b28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-2.4.0-gc2f53117-0afb5e9-sources.jar",
          "url": "coakka-quarkus-extension-2.4.0-gc2f53117-0afb5e9-sources.jar",
          "size": 5737,
          "sha512": "0795951c883846cc191eecb405c00382bc5ec6c1bb2d88907696d3ec4fc442e73a5965f18e7d937056d44d6c3f77b7474e0c82ba45cddb3b572aeb7f2f9d4db8",
          "sha256": "caed59696ad29345fa62afe66deeee663f76423a9e14bf2d82aa7a50b3c11d8d",
          "sha1": "43bd48565053c08c0de108a5b578b729a0e54ed6",
          "md5": "65b46a41d7ceb977234b74c43d16dd1c"
        }
      ]
    }
  ]
}
