{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.spring",
    "module": "coakka-spring-boot-starter",
    "version": "1.3.3-g282f3ad-657ec79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.3-g282f3ad-657ec79"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-1.3.3-g282f3ad-657ec79.jar",
          "url": "coakka-spring-boot-starter-1.3.3-g282f3ad-657ec79.jar",
          "size": 10989,
          "sha512": "63ab00fc4f8248cffae5e3a734b74c7eea13602f3825dd749cb88c6d155252464178b482d33c2e2d411b2a191931f31ef97252b0f2632b99673734261086ce88",
          "sha256": "b7ddd3bd8217cd1d03ae9ea7019679eaa3405cbdd83aae2a56fc0daa5bd914b0",
          "sha1": "7ca64612d31febb3d528917e28de8c4700577042",
          "md5": "a920d9ecbff4f5c000946bdf652d9304"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.3-g282f3ad-657ec79"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        }
      ],
      "files": [
        {
          "name": "coakka-spring-boot-starter-1.3.3-g282f3ad-657ec79.jar",
          "url": "coakka-spring-boot-starter-1.3.3-g282f3ad-657ec79.jar",
          "size": 10989,
          "sha512": "63ab00fc4f8248cffae5e3a734b74c7eea13602f3825dd749cb88c6d155252464178b482d33c2e2d411b2a191931f31ef97252b0f2632b99673734261086ce88",
          "sha256": "b7ddd3bd8217cd1d03ae9ea7019679eaa3405cbdd83aae2a56fc0daa5bd914b0",
          "sha1": "7ca64612d31febb3d528917e28de8c4700577042",
          "md5": "a920d9ecbff4f5c000946bdf652d9304"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-spring-boot-starter-1.3.3-g282f3ad-657ec79-sources.jar",
          "url": "coakka-spring-boot-starter-1.3.3-g282f3ad-657ec79-sources.jar",
          "size": 5220,
          "sha512": "c66c355532a0711bcc46f7054cf563dbe7e4f63f0dfb2b0dd719460ee2dad3643b2ed9b11e38a06e8247bda81b2102d8a3f22def6e03acb3f6cb2ba82400f5bc",
          "sha256": "b14835ae7c6889624ac3eee234556957e6e8371adbcc2cb53c4c49395f1ae959",
          "sha1": "f2e3d924c3170e0eab8ff000c731110ff2840766",
          "md5": "ef009634362dc12c937d61df56215f21"
        }
      ]
    }
  ]
}
