{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "1.3.1-g0da8c2d9-8ff6f32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.3.1-g0da8c2d9-8ff6f32.jar",
          "url": "coakka-jvm-native-runtime-v2-1.3.1-g0da8c2d9-8ff6f32.jar",
          "size": 15625661,
          "sha512": "34034f2f505c91c9b1a0571a18e29f3837ffb3b46e11734e793a8aa4e2cfec149c134d12139f2ee2dd2f2fbbb89923e9a412e7d56e5a0e25dca63243ebcb35a4",
          "sha256": "8dc0b348a7140eddfcc9d107c0f8e8b5b22cda6d12ac7f9d14231f17b2607f60",
          "sha1": "147a9a00bd23b707e9ae0011e4341020c2dd8fe5",
          "md5": "099b83e78ca25e49e0167c52538d1a25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.3.1-g0da8c2d9-8ff6f32.jar",
          "url": "coakka-jvm-native-runtime-v2-1.3.1-g0da8c2d9-8ff6f32.jar",
          "size": 15625661,
          "sha512": "34034f2f505c91c9b1a0571a18e29f3837ffb3b46e11734e793a8aa4e2cfec149c134d12139f2ee2dd2f2fbbb89923e9a412e7d56e5a0e25dca63243ebcb35a4",
          "sha256": "8dc0b348a7140eddfcc9d107c0f8e8b5b22cda6d12ac7f9d14231f17b2607f60",
          "sha1": "147a9a00bd23b707e9ae0011e4341020c2dd8fe5",
          "md5": "099b83e78ca25e49e0167c52538d1a25"
        }
      ]
    }
  ]
}
