{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "1.4.0-g2cee86bf-ec4902c",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.4.0-g2cee86bf-ec4902c.jar",
          "url": "coakka-jvm-native-runtime-v2-1.4.0-g2cee86bf-ec4902c.jar",
          "size": 23394115,
          "sha512": "a8426660789b131ad407953196fcbfd601a36eaab606b6f0282ca9ebbeb743b2995cca5e5f49661b061dd5f25ba794543e850bdfd72a8ad41f8c4ab600f9d34e",
          "sha256": "f4db97776adbfe31c4dc834869abad78272d6576cfa531be9b0581a86d02c613",
          "sha1": "d39872bc67780c5c74f0b8ed9fc17c0bc812987c",
          "md5": "e4cfd983865129bcb7651f9b38a8df31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-1.4.0-g2cee86bf-ec4902c.jar",
          "url": "coakka-jvm-native-runtime-v2-1.4.0-g2cee86bf-ec4902c.jar",
          "size": 23394115,
          "sha512": "a8426660789b131ad407953196fcbfd601a36eaab606b6f0282ca9ebbeb743b2995cca5e5f49661b061dd5f25ba794543e850bdfd72a8ad41f8c4ab600f9d34e",
          "sha256": "f4db97776adbfe31c4dc834869abad78272d6576cfa531be9b0581a86d02c613",
          "sha1": "d39872bc67780c5c74f0b8ed9fc17c0bc812987c",
          "md5": "e4cfd983865129bcb7651f9b38a8df31"
        }
      ]
    }
  ]
}
