{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "1.4.1-g9e02a51d-4e7cda4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.4.1-g9e02a51d-4e7cda4"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.4.1-g9e02a51d-4e7cda4.jar",
          "url": "coakka-quarkus-extension-1.4.1-g9e02a51d-4e7cda4.jar",
          "size": 10820,
          "sha512": "ef038c8c0f4f52cdd6470cba29e4a05674ae66cdc7b02330f5e07e6b888c89017c371b890378727ff409a9387dac01bea8fcdd832f04660baaff1404676f30ea",
          "sha256": "9d67900cba35a3aaa2bd2887d832b6e41d73e4dcb960d9c8a9540d4ab22e25ff",
          "sha1": "b76b1d7c7c0576ddd43394a25bc29cac9aabf25c",
          "md5": "f7655ff7dc84e4b9c5a86df456641cfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.4.1-g9e02a51d-4e7cda4"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.4.1-g9e02a51d-4e7cda4.jar",
          "url": "coakka-quarkus-extension-1.4.1-g9e02a51d-4e7cda4.jar",
          "size": 10820,
          "sha512": "ef038c8c0f4f52cdd6470cba29e4a05674ae66cdc7b02330f5e07e6b888c89017c371b890378727ff409a9387dac01bea8fcdd832f04660baaff1404676f30ea",
          "sha256": "9d67900cba35a3aaa2bd2887d832b6e41d73e4dcb960d9c8a9540d4ab22e25ff",
          "sha1": "b76b1d7c7c0576ddd43394a25bc29cac9aabf25c",
          "md5": "f7655ff7dc84e4b9c5a86df456641cfa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-1.4.1-g9e02a51d-4e7cda4-sources.jar",
          "url": "coakka-quarkus-extension-1.4.1-g9e02a51d-4e7cda4-sources.jar",
          "size": 5737,
          "sha512": "0795951c883846cc191eecb405c00382bc5ec6c1bb2d88907696d3ec4fc442e73a5965f18e7d937056d44d6c3f77b7474e0c82ba45cddb3b572aeb7f2f9d4db8",
          "sha256": "caed59696ad29345fa62afe66deeee663f76423a9e14bf2d82aa7a50b3c11d8d",
          "sha1": "43bd48565053c08c0de108a5b578b729a0e54ed6",
          "md5": "65b46a41d7ceb977234b74c43d16dd1c"
        }
      ]
    }
  ]
}
