{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.quarkus",
    "module": "coakka-quarkus-extension",
    "version": "1.3.1-g0da8c2d9-8ff6f32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.1-g0da8c2d9-8ff6f32"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.3.1-g0da8c2d9-8ff6f32.jar",
          "url": "coakka-quarkus-extension-1.3.1-g0da8c2d9-8ff6f32.jar",
          "size": 9509,
          "sha512": "eaa23d5cca63c0a07b2914b386b9e78dc9424e1f11a647c13ba5f8d27bd30c50f5a33e0c9f090f8311a09cb4ffb0eb1c818ce33c58e56abfd3aaa1f9bca70594",
          "sha256": "0ef67665cc926e964899486aaa0c8d5ecaa5219d559f38d911d1244ec7127c18",
          "sha1": "eaf13f04937a9b416d45019021f19c71336bcbcb",
          "md5": "0d30ac1b7531fe7dfecd9da46bd69b03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.quarkus.platform",
          "module": "quarkus-bom",
          "version": {
            "requires": "3.35.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "coakka.v2",
          "module": "coakka-jvm-native-runtime-v2",
          "version": {
            "requires": "1.3.1-g0da8c2d9-8ff6f32"
          }
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-arc"
        },
        {
          "group": "io.quarkus",
          "module": "quarkus-jackson"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        }
      ],
      "files": [
        {
          "name": "coakka-quarkus-extension-1.3.1-g0da8c2d9-8ff6f32.jar",
          "url": "coakka-quarkus-extension-1.3.1-g0da8c2d9-8ff6f32.jar",
          "size": 9509,
          "sha512": "eaa23d5cca63c0a07b2914b386b9e78dc9424e1f11a647c13ba5f8d27bd30c50f5a33e0c9f090f8311a09cb4ffb0eb1c818ce33c58e56abfd3aaa1f9bca70594",
          "sha256": "0ef67665cc926e964899486aaa0c8d5ecaa5219d559f38d911d1244ec7127c18",
          "sha1": "eaf13f04937a9b416d45019021f19c71336bcbcb",
          "md5": "0d30ac1b7531fe7dfecd9da46bd69b03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-quarkus-extension-1.3.1-g0da8c2d9-8ff6f32-sources.jar",
          "url": "coakka-quarkus-extension-1.3.1-g0da8c2d9-8ff6f32-sources.jar",
          "size": 5110,
          "sha512": "e4cc5d8c196f6d1ce2f0329b001023494b82de037fc538399d49bc8a580d763d2fa6580c1269f8725c775795f2bd1ebe6677b54b39d2c758338dcf3fffea025c",
          "sha256": "df23a1f08d87eef6944f45bfca6a5e3f62c46035872755b7d0d9663e40e74962",
          "sha1": "c62d715a944c2e8ce87a497575967b2c7b8be25f",
          "md5": "d98bcfeeac12753f90c4dfba7ae81edc"
        }
      ]
    }
  ]
}
