{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.1.1-g3362b67",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.1-g3362b67.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.1-g3362b67.jar",
          "size": 10161304,
          "sha512": "594d1f4340a0f4f31e0bc89d22c12b0d07e73141d2f8455e3e76a0d24371c906741f358e12b352140aad8ec0ddccce8710c19ea3f8fae9d16fb2815166edfe4e",
          "sha256": "ba3ecdea428de2a1a7f48ce8443c7718dcc1f7c95c3c3279a9f21f7ac816ec3c",
          "sha1": "3f8973c669c2942fcfa07b9023023ca2f5eabda3",
          "md5": "e0540ac217378dfb404a6eccfec769b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.1.1-g3362b67.jar",
          "url": "coakka-jvm-native-runtime-v2-0.1.1-g3362b67.jar",
          "size": 10161304,
          "sha512": "594d1f4340a0f4f31e0bc89d22c12b0d07e73141d2f8455e3e76a0d24371c906741f358e12b352140aad8ec0ddccce8710c19ea3f8fae9d16fb2815166edfe4e",
          "sha256": "ba3ecdea428de2a1a7f48ce8443c7718dcc1f7c95c3c3279a9f21f7ac816ec3c",
          "sha1": "3f8973c669c2942fcfa07b9023023ca2f5eabda3",
          "md5": "e0540ac217378dfb404a6eccfec769b7"
        }
      ]
    }
  ]
}
