{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-jvm-native-runtime-v2",
    "version": "0.2.0-gc124a9e-da30a95",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gc124a9e-da30a95.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gc124a9e-da30a95.jar",
          "size": 8087288,
          "sha512": "e2690aab3d9a775f5692c5533c42a41c99f67eaf9cfe63e9b3025dc24c31742112be4f196d901a826c23ea8e70ef4fe1040916ddab8e97644eb6bdbf9f2316ff",
          "sha256": "24a9bb3f0cc1ff7a61a7a3d6e529fe3528236bbe3bf11a2d01d644a7bf1411bc",
          "sha1": "02e359d736adb210864102a07f4f2c7a067bf8dc",
          "md5": "516ec159a48cab1037cb2d3e4a9becb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-jvm-native-runtime-v2-0.2.0-gc124a9e-da30a95.jar",
          "url": "coakka-jvm-native-runtime-v2-0.2.0-gc124a9e-da30a95.jar",
          "size": 8087288,
          "sha512": "e2690aab3d9a775f5692c5533c42a41c99f67eaf9cfe63e9b3025dc24c31742112be4f196d901a826c23ea8e70ef4fe1040916ddab8e97644eb6bdbf9f2316ff",
          "sha256": "24a9bb3f0cc1ff7a61a7a3d6e529fe3528236bbe3bf11a2d01d644a7bf1411bc",
          "sha1": "02e359d736adb210864102a07f4f2c7a067bf8dc",
          "md5": "516ec159a48cab1037cb2d3e4a9becb0"
        }
      ]
    }
  ]
}
