{
  "formatVersion": "1.1",
  "component": {
    "group": "coakka.v2",
    "module": "coakka-runtime-android",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-runtime-android-1.1.0.aar",
          "url": "coakka-runtime-android-1.1.0.aar",
          "size": 2419500,
          "sha512": "d7eacd1f31597d0979d8011f5222a64c9a5a123e2d8d4631319d39697a9e358ce1091547425393ed5996cd6f6cbd118eceb0d696f70bb1f9bc91dcea99c6dea8",
          "sha256": "3ce799885322c9ac92664bf028591bc77432960e7b2d85ecbd3c4e73362bf3cb",
          "sha1": "b02d5c7d960a9b24f6bfcc49d47d2c312da3880f",
          "md5": "ea5e7a8d9528d021330123ed1af7f6a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "coakka-runtime-android-1.1.0.aar",
          "url": "coakka-runtime-android-1.1.0.aar",
          "size": 2419500,
          "sha512": "d7eacd1f31597d0979d8011f5222a64c9a5a123e2d8d4631319d39697a9e358ce1091547425393ed5996cd6f6cbd118eceb0d696f70bb1f9bc91dcea99c6dea8",
          "sha256": "3ce799885322c9ac92664bf028591bc77432960e7b2d85ecbd3c4e73362bf3cb",
          "sha1": "b02d5c7d960a9b24f6bfcc49d47d2c312da3880f",
          "md5": "ea5e7a8d9528d021330123ed1af7f6a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coakka-runtime-android-1.1.0-sources.jar",
          "url": "coakka-runtime-android-1.1.0-sources.jar",
          "size": 56038,
          "sha512": "59bc166883edf76f2c4b06168e2833d768d694ce2c6c6bb8a0871395a849853769378d161809ce6b550aec08e6697ab05fbb562628406ef874238e9477681d47",
          "sha256": "c1328df885e519102e3f4338f094244a8c7370d0dde05479dc2dac748bb4fe47",
          "sha1": "5aa2fe81078537982ba452b03a6c12df777f0bde",
          "md5": "887ad7096451fd258be0d768b8ef3a48"
        }
      ]
    }
  ]
}
